# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'StudentCompanion' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for StudentCompanion
  pod 'React', :path => '../node_modules/react-native/'
  pod 'React-Core', :path => '../node_modules/react-native/React'
  pod 'React-DevSupport', :path => '../node_modules/react-native/React'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
  pod 'React-RCTWebSocket', :path => '../node_modules/react-native/Libraries/WebSocket'


  # pod 'React', :path => '../node_modules/react-native', :subspecs => [
  #   'Core',
  #   'CxxBridge',
  #   'DevSupport',
  #   'RCTText',
  #   'RCTImage',
  #   'RCTNetwork',
  #   'RCTWebSocket'
  # ]

  pod "yoga", :path => "../node_modules/react-native/ReactCommon/yoga"
  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'

  pod 'Firebase/Analytics'
  pod 'GoogleAnalytics'
  pod 'Firebase'
  pod 'Firebase/Core', '~> 6.3.0'
  pod 'Firebase/Auth', '~> 6.3.0'
  pod 'Firebase/Database'
  pod 'Firebase/Functions'
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'Firebase/Messaging'

  pod 'react-native-fetch-blob',
    :path => '../node_modules/react-native-fetch-blob'

  pod 'react-native-camera-kit', :path => '../node_modules/react-native-camera-kit'

  pod 'RNFS', :path => '../node_modules/react-native-fs'

  pod 'RSKImageCropper'
  pod 'QBImagePickerController'

  # Third party deps podspec link
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'

  pod 'react-native-netinfo', :path => '../node_modules/@react-native-community/netinfo'

  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  pod 'RNImageCropPicker', :path => '../node_modules/react-native-image-crop-picker'

  pod 'RNFirebase', :path => '../node_modules/react-native-firebase/ios'

  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

  pod 'TextToSpeech', :path => '../node_modules/react-native-tts'

  pod 'react-native-randombytes', :path => '../node_modules/react-native-randombytes'

  pod 'react-native-fcm', :path => '../node_modules/react-native-fcm'

  pod 'RNScreens', :path => '../node_modules/react-native-screens'

  pod 'react-native-webview', :path => '../node_modules/react-native-webview'

  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'

  pod 'react-native-paystack', :path => '../node_modules/react-native-paystack'

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  target 'StudentCompanionTests' do
    inherit! :search_paths
    # Pods for testing
  end
end

target 'StudentCompanion-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for StudentCompanion-tvOS

  target 'StudentCompanion-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    # Build React Native with DEBUG enabled
    if target.name == 'React'
      target.build_configurations.each do |config|
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= []
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'DEBUG=1'
      end
    end
  end
end
